kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oracle-pvc
  annotations:
    pv.beta.kubernetes.io/gid: "54321"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2